package edu.training_student_management_system.dto;

import java.util.List;

import org.springframework.stereotype.Component;

import edu.training_student_management_system.entity.Student;
import lombok.Getter;
import lombok.Setter;


//interact b/w client(postman) and api
//not interact b/w Db and api

//reasons for dto class

//1. to hide secure attribute(eg:password) while returning obj


//2. while taking value from client itself...
//that is if we want to take limited attribute values..
//if several attributes present
//eg:   for a movie
//    show start time, seat price, gold seat price given as input, wch are present in dto 
// that is... wat are the attributes should be entered by client are present in dto
// but in o/p we get autogenerated attributes like show runtime,showid,show status, show location,movie duration like that 
// all these attributes are present in entity


//@component- obj should be generated by springboot

@Component
@Getter
@Setter
public class AdminDto {
	//variable should be same as entity class,dao and should not contain....
	// secure data like password
	// password will not be get as o/p in postman
	
	private int adminId;
	private String adminName;
	private String adminEmail;
	
	
	private List<Student> students;// having list in dto is option.. not mandatory
}
